server:
  port: 8787
  servlet:
    context-path: /clockin
spring:
  datasource:
    url: jdbc:mysql:///clockin?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: long
wxapp:
  appid: wx0c9789a8be812194
  secret: 9d2b7f0025ccba2831ffb433dd3e3ff6
  grant_type: authorization_code